quote: EUR
symbols: [BTC, ETH, ADA, SOL, XRP]

# Signalen
timeframe: "5m"
sma_fast: 9
sma_slow: 21
signals_mode: sma
signals_url: ""

# Inzet
fixed_stake_quote: 15
stake_fraction: 0.10

# Limieten
max_open_positions: 50
only_buy_if_not_in_position: true
single_open_buy_per_coin: true
cooldown_minutes: 15

# Trailing Stop-Buy
tsb_enabled: false
tsb_trail_pct: 1.0

# DCA
dca_enabled: false
dca_steps: 3
dca_drop_pct: 5.0
dca_stake_multiplier: 1.0

# Verkopen
sell_enabled: true
manage_only_own_positions: true
sell_on_cross: true
tp_pct: 2
tsl_pct: 3

sleep_seconds: 30
