# Bitvavo CH-bot configuratie
quote: EUR
symbols: [BTC, ETH, ADA, SOL, XRP]
timeframe: "15m"
sma_fast: 20
sma_slow: 50

# Signalen
signals_mode: sma          # sma | external
signals_url: ""            # bij external: JSON {"buy":["BTC/EUR"], "sell":["ETH/EUR"]}

# Inzet
fixed_stake_quote: 0       # 0 = uit
stake_fraction: 0.05       # 5% van vrij EUR

# Limieten
max_open_positions: 50
max_pct_per_coin: 2
only_buy_if_not_in_position: true
single_open_buy_per_coin: true
cooldown_minutes: 30

# Trailing Stop-Buy
tsb_enabled: false
tsb_trail_pct: 1.0

# DCA
dca_enabled: false
dca_steps: 3
dca_drop_pct: 5.0
dca_stake_multiplier: 1.0

# Verkopen (gebalanceerd: TP 2%, TSL 3%)
sell_enabled: true
manage_only_own_positions: true   # verkoop alleen posities gekocht door deze bot
sell_on_cross: false
tp_pct: 2
tsl_pct: 3

# Loop
sleep_seconds: 60
