sell_enabled: true
signals_mode: sma         # of external met je eigen signal feed
tsb_enabled: true
tsb_trail_pct: 1.0
tp_pct: 2                 # voorbeeld
tsl_pct: 3                # voorbeeld
sell_on_cross: false      # rely op TP/TSL
dca_enabled: true
dca_steps: 3
dca_drop_pct: 5
dca_stake_multiplier: 1.2
only_buy_if_not_in_position: true
single_open_buy_per_coin: true
